services:
  mysql:
    image: mysql:8.0
    container_name: tm_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123123"
      MYSQL_DATABASE: task_manager_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p123123"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./task-manager
    container_name: tm_backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_URL: jdbc:mysql://mysql:3306/task_manager_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&characterEncoding=UTF-8
      DB_USERNAME: root
      DB_PASSWORD: "123123"
      JWT_SECRET: "DvesKB8aSaH1GJ3ZZQA48wZYv0cPo0DBA9TRmnLwBh5"
      JWT_EXPIRATION: "86400000"
      FRONTEND_URL: "http://localhost:5173"
      UPLOAD_DIR: /app/uploads
    ports:
      - "8080:8080"
    volumes:
      - uploads_data:/app/uploads

  frontend:
    build:
      context: ./task-manager-fe
      args:
        VITE_API_BASE_URL: http://localhost:8080
    container_name: tm_frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  mysql_data:
  uploads_data: